<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula11a_ensembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import fetch_olivetti_faces
from sklearn.model_selection import train_test_split
X, y = fetch_olivetti_faces(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_hits = (knn_pred == y_test)
print(knn_hits)
print(knn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.8625


In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)
gnb_hits = (gnb_pred == y_test)
print(gnb_hits)
print(gnb_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True False  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True False  True  True  True  True  True
  True False  True  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True False  True False  True  True
  True  True  True  True  True  True False  True]
0.8375


In [7]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(eta0=0.1, random_state=42)
ppn.fit(X_train, y_train)
ppn_pred = ppn.predict(X_test)
ppn_hits = (ppn_pred == y_test)
print(ppn_hits)
print(ppn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True False  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
 False  True  True  True  True  True  True  True]
0.875


In [8]:
import numpy as np
hits = np.stack([knn_hits, gnb_hits, ppn_hits])
print(hits.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False  True  True]
 [ True  True False]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [12]:
y_pred = np.array([knn_pred, gnb_pred, ppn_pred])
print(y_pred.T)

[[20 20 20]
 [28 28 28]
 [ 3  3  3]
 [21 21 21]
 [ 9  9  9]
 [ 8  8  8]
 [32 32 32]
 [ 9  9  9]
 [26 26 26]
 [12 16 12]
 [ 0  0 36]
 [36 36 36]
 [ 5  5  5]
 [ 7 15  7]
 [13 13 13]
 [ 4 34  4]
 [27 27 27]
 [37 37 37]
 [23 23 23]
 [38 38 38]
 [ 7  9  7]
 [ 1  1  1]
 [ 4 39 39]
 [25 27 27]
 [ 0  0  0]
 [ 3 39 39]
 [ 8 11 11]
 [22 22 22]
 [26 26 26]
 [10 15 10]
 [39 39 39]
 [14 19 19]
 [26 26 26]
 [ 5  5  5]
 [23 23 23]
 [11 11 11]
 [12 25 13]
 [20 34 34]
 [15 15 34]
 [14 14 14]
 [38 38 18]
 [ 5  5  5]
 [ 7  9  7]
 [ 2  2  9]
 [ 8  8  8]
 [38 38 38]
 [14 14 14]
 [18 18 18]
 [ 2  2  2]
 [17 39 17]
 [ 4  4 33]
 [32 32 32]
 [33 33 33]
 [ 7  9  7]
 [37 37 37]
 [ 3  3 24]
 [22 22 22]
 [17 17 17]
 [ 3  3  3]
 [ 0 15 15]
 [12 12 12]
 [29 29 29]
 [25 25 32]
 [17  0  7]
 [10 10 10]
 [14  3  3]
 [35 35 35]
 [26 12 27]
 [37 39 39]
 [ 7  9  7]
 [32 32 32]
 [14 14 14]
 [ 0  0 34]
 [ 4  4  4]
 [38 38 38]
 [24 24 24]
 [22 22 22]
 [36 36 36]
 [17  9 17]
 [28 28 28]]


In [13]:
from scipy.stats import mode
y_pred_mode, _ = mode(y_pred, axis=0)
vote_hits = (y_pred_mode == y_test)
print(vote_hits)
print(vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [14]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers):
        self.classifiers = classifiers

    def fit(self, X, y):
        for _, clf in self.classifiers:
            clf.fit(X, y)
        return self

    def predict(self, X):
        y_preds = np.array([clf.predict(X) for _, clf in self.classifiers])
        y_pred_mode, _ = mode(y_preds, axis=0)
        return y_pred_mode

weak_estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
]
vote_clf = MajorityVoteClassifier(weak_estimators)
vote_clf.fit(X_train, y_train)
vote_pred = vote_clf.predict(X_test)
vote_hits = (vote_pred == y_test)
print(vote_hits)
print(vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [15]:
from sklearn.ensemble import VotingClassifier

voting_clf = VotingClassifier(weak_estimators)
voting_clf.fit(X_train, y_train)
voting_pred = voting_clf.predict(X_test)
voting_hits = (voting_pred == y_test)
print(voting_hits)
print(voting_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [26]:
ks = [1, 5, 9]
weak_estimators = [(f"KNN({k})", KNeighborsClassifier(k)) for k in ks]
voting_clf = VotingClassifier(weak_estimators)
voting_clf.fit(X_train, y_train)
voting_pred = voting_clf.predict(X_test)
voting_hits = (voting_pred == y_test)
print(voting_hits)
print(voting_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.875


In [29]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)
tree_pred = tree_clf.predict(X_test)
tree_hits = (tree_pred == y_test)
print(tree_hits)
print(tree_hits.mean())

[ True  True  True  True  True False  True False False False False  True
  True False False False False  True  True False  True  True False False
  True  True False False False  True False  True  True False False False
 False False False  True False  True False False  True False  True  True
  True False False  True  True False  True False False False False  True
 False  True False False  True  True  True  True False False  True False
 False  True False  True  True False  True  True]
0.475


In [30]:
weak_estimators = [(f"dt{i+1}", DecisionTreeClassifier()) for i in range(3)]
voting_clf = VotingClassifier(weak_estimators)
voting_clf.fit(X_train, y_train)
voting_pred = voting_clf.predict(X_test)
voting_hits = (voting_pred == y_test)
print(voting_hits)
print(voting_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False False  True  True  True  True  True False False
  True  True False False False False False  True  True False  True False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False  True  True  True False False False  True False
 False False  True  True  True False  True  True]
0.5


In [31]:
weak_estimators = [(f"dt{i+1}", DecisionTreeClassifier()) for i in range(10)]
voting_clf = VotingClassifier(weak_estimators)
voting_clf.fit(X_train, y_train)
voting_pred = voting_clf.predict(X_test)
voting_hits = (voting_pred == y_test)
print(voting_hits)
print(voting_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False False  True  True  True  True  True False False
  True  True False False False  True False  True  True False False False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False  True  True  True  True False False  True False
 False  True  True  True  True False  True  True]
0.525


In [40]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(splitter='random')
tree_clf.fit(X_train, y_train)
tree_pred = tree_clf.predict(X_test)
tree_hits = (tree_pred == y_test)
print(tree_hits)
print(tree_hits.mean())

[ True  True  True False  True False False  True  True False False  True
  True  True  True False False  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False  True False  True False  True False False  True  True
  True  True  True  True  True False  True False False  True  True False
 False  True False False False  True False  True  True False False  True
 False  True  True  True False  True  True  True]
0.6375


In [46]:
weak_estimators = [(f"dt{i+1}", DecisionTreeClassifier(splitter='random')) for i in range(10)]
voting_clf = VotingClassifier(weak_estimators)
voting_clf.fit(X_train, y_train)
voting_pred = voting_clf.predict(X_test)
voting_hits = (voting_pred == y_test)
print(voting_hits)
print(voting_hits.mean())

[ True  True  True  True  True False  True  True  True False False  True
  True  True  True  True False  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False  True False  True False  True  True False  True  True
  True  True  True  True  True False  True False False  True  True  True
  True  True False False  True  True  True  True False False  True  True
  True  True  True  True  True False  True  True]
0.7625


In [47]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier()
bagging_clf = BaggingClassifier(base_estimator, n_estimators=10)
bagging_clf.fit(X_train, y_train)
bagging_pred = bagging_clf.predict(X_test)
bagging_hits = (bagging_pred == y_test)
print(bagging_hits)
print(bagging_hits.mean())

[ True  True  True  True  True  True  True False  True False  True  True
  True  True  True  True False  True  True  True  True  True  True False
  True  True  True False  True False False  True  True  True  True  True
 False False  True  True False  True  True False  True False  True  True
  True  True False  True  True  True  True False False  True  True  True
  True  True False False  True  True  True  True False False  True  True
  True  True  True  True  True False False  True]
0.7375


In [53]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier(splitter='random')
bagging_clf = BaggingClassifier(base_estimator,
                                n_estimators=100,
                                random_state=42)
bagging_clf.fit(X_train, y_train)
bagging_pred = bagging_clf.predict(X_test)
bagging_hits = (bagging_pred == y_test)
print(bagging_hits)
print(bagging_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.9125


In [54]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)
rf_hits = (rf_pred == y_test)
print(rf_hits)
print(rf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True False False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.925


In [55]:
from sklearn.ensemble import ExtraTreesClassifier

et_clf = ExtraTreesClassifier(n_estimators=100, random_state=42)
et_clf.fit(X_train, y_train)
et_pred = et_clf.predict(X_test)
et_hits = (et_pred == y_test)
print(et_hits)
print(et_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [65]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(DecisionTreeClassifier(splitter='random', max_depth=20),
                             random_state=42)
ada_clf.fit(X_train, y_train)
ada_pred = ada_clf.predict(X_test)
ada_hits = (ada_pred == y_test)
print(ada_hits)
print(ada_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.9375


In [71]:
from sklearn.ensemble import StackingClassifier
import warnings
warnings.filterwarnings('ignore')

base_estimators = [
    ('ab', ada_clf),
    ('rf', rf_clf),
    ('et', et_clf)
  ]

stacking_clf = StackingClassifier(base_estimators,
                                  cv=5)
stacking_clf.fit(X_train, y_train)
stacking_pred = stacking_clf.predict(X_test)
stacking_hits = (stacking_pred == y_test)
print(stacking_hits)
print(stacking_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True False  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True False  True False False  True False  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.825


In [75]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate, StratifiedKFold

et_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('et', ExtraTreesClassifier(n_estimators=100, random_state=42))
])

scores = cross_validate(et_pipe, X, y,
                        cv=StratifiedKFold(shuffle=True, random_state=42))
print(scores['test_score'])
print(scores['test_score'].mean())

[0.95   0.9625 0.9875 0.95   0.95  ]
0.9600000000000002


In [76]:
from sklearn.linear_model import LogisticRegression

lr_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LogisticRegression(random_state=42))
])

scores = cross_validate(lr_pipe, X, y,
                        cv=StratifiedKFold(shuffle=True, random_state=42))
print(scores['test_score'])
print(scores['test_score'].mean())

[0.9875 0.975  0.975  0.975  0.9625]
0.975
