<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula11a_m%C3%A9tricas_de_classifica%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import load_wine
import numpy as np

X, y = load_wine(return_X_y=True)
print(X.shape)
print()

(178, 13)



In [4]:
unique_labels, counts = np.unique(y, return_counts=True)
print("Label counts:")
for label, count in zip(unique_labels, counts):
    print(f"Label {label}: {count}")

Label counts:
Label 0: 59
Label 1: 71
Label 2: 48


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.78      0.74         9
           1       0.76      0.81      0.79        16
           2       0.78      0.64      0.70        11

    accuracy                           0.75        36
   macro avg       0.75      0.74      0.74        36
weighted avg       0.75      0.75      0.75        36

[[ 7  1  1]
 [ 2 13  1]
 [ 1  3  7]]


In [12]:
precisao_label0 = 7/(7+2+1)
print(f"precisão label 0: {precisao_label0:.2f}")
precisao_label1 = 13/(1+13+3)
print(f"precisão label 1: {precisao_label1:.2f}")
precisao_label2 = 7/(1+1+7)
print(f"precisão label 2: {precisao_label2:.2f}")

precisão label 0: 0.70
precisão label 1: 0.76
precisão label 2: 0.78


# Falha em conseguir recall alto

In [26]:
positivos = 10
negativos = 990
positivos_porcentagem = positivos / (positivos + negativos) * 100
print(f"Porcentagem de positivos: {positivos_porcentagem:.2f}%")
negativos_porcentagem = negativos / (positivos + negativos) * 100
print(f"Porcentagem de negativos: {negativos_porcentagem:.2f}%")

###########
# 1 # 9   #
# 0 # 990 #
###########

verdadeiro_positivo = 1
vedadeiro_negativo = 990
falso_positivo = 0
falso_negativo = 9

print()

accuracia = (verdadeiro_positivo + vedadeiro_negativo) / (positivos + negativos)
print(f"Acurácia: {accuracia}")

precisao = verdadeiro_positivo / (verdadeiro_positivo + falso_positivo)
print(f"Precisão: {precisao}")

recall = verdadeiro_positivo / positivos
print(f"Recall: {recall}")

Porcentagem de positivos: 1.00%
Porcentagem de negativos: 99.00%

Acurácia: 0.991
Precisão: 1.0
Recall: 0.1


# Conseguindo recall alto

In [29]:
positivos = 10
negativos = 990
positivos_porcentagem = positivos / (positivos + negativos) * 100
print(f"Porcentagem de positivos: {positivos_porcentagem:.2f}%")
negativos_porcentagem = negativos / (positivos + negativos) * 100
print(f"Porcentagem de negativos: {negativos_porcentagem:.2f}%")

############
# 10 # 0   #
# 90 # 900 #
############

verdadeiro_positivo = 10
vedadeiro_negativo = 900
falso_positivo = 90
falso_negativo = 0

print()

accuracia = (verdadeiro_positivo + vedadeiro_negativo) / (positivos + negativos)
print(f"Acurácia: {accuracia}")

precisao = verdadeiro_positivo / (verdadeiro_positivo + falso_positivo)
print(f"Precisão: {precisao}")

recall = verdadeiro_positivo / positivos
print(f"Recall: {recall}")

Porcentagem de positivos: 1.00%
Porcentagem de negativos: 99.00%

Acurácia: 0.91
Precisão: 0.1
Recall: 1.0


# Conseguindo precisão alta às custas de recall baixo

In [33]:
positivos = 100
negativos = 900
positivos_porcentagem = positivos / (positivos + negativos) * 100
print(f"Porcentagem de positivos: {positivos_porcentagem:.2f}%")
negativos_porcentagem = negativos / (positivos + negativos) * 100
print(f"Porcentagem de negativos: {negativos_porcentagem:.2f}%")

############
# 1  # 99  #
# 0  # 900 #
############

verdadeiro_positivo = 1
vedadeiro_negativo = 900
falso_positivo = 0
falso_negativo = 99

print()

accuracia = (verdadeiro_positivo + vedadeiro_negativo) / (positivos + negativos)
print(f"Acurácia: {accuracia}")

precisao = verdadeiro_positivo / (verdadeiro_positivo + falso_positivo)
print(f"Precisão: {precisao}")

recall = verdadeiro_positivo / positivos
print(f"Recall: {recall}")

Porcentagem de positivos: 10.00%
Porcentagem de negativos: 90.00%

Acurácia: 0.901
Precisão: 1.0
Recall: 0.01


# F1-score

In [34]:
# Média harmônica da precisão e da revocação

f1_score = (2 * precisao * recall)/(precisao + recall)
print(f"F1-score: {f1_score}")

F1-score: 0.019801980198019802


In [40]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score

print(classification_report(y_test, y_pred))
print(f"Acurácia: {accuracy_score(y_test, y_pred):.2f}")
print(f"Precisão: {precision_score(y_test, y_pred, average='macro'):.2f}")
print(f"Recall: {recall_score(y_test, y_pred, average='macro'):.2f}")
print(f"F1-score: {f1_score(y_test, y_pred, average='macro'):.2f}")
print(f"F-beta = 0.1: {fbeta_score(y_test, y_pred, beta=0.1, average='macro'):.5f}")
print(f"F-beta = 1.0: {fbeta_score(y_test, y_pred, beta=1.0, average='macro'):.5f}")
print(f"F-beta = 100: {fbeta_score(y_test, y_pred, beta=100, average='macro'):.5f}")

              precision    recall  f1-score   support

           0       0.70      0.78      0.74         9
           1       0.76      0.81      0.79        16
           2       0.78      0.64      0.70        11

    accuracy                           0.75        36
   macro avg       0.75      0.74      0.74        36
weighted avg       0.75      0.75      0.75        36

Acurácia: 0.75
Precisão: 0.75
Recall: 0.74
F1-score: 0.74
F-beta = 0.1: 0.74731
F-beta = 1.0: 0.74157
F-beta = 100: 0.74221
