<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula13a_falha_no_3fold_para_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [2]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()

kf = KFold(n_splits=3, shuffle=False)

scores = cross_val_score(clf, X, y, cv=kf)
print(scores)

[0. 0. 0.]


In [8]:
for tr_idxs, te_idxs in kf.split(X):
    print(f"Training classes: {set(y[tr_idxs])}")
    print(f"Testing classes: {set(y[te_idxs])}")

Training classes: {np.int64(1), np.int64(2)}
Testing classes: {np.int64(0)}
Training classes: {np.int64(0), np.int64(2)}
Testing classes: {np.int64(1)}
Training classes: {np.int64(0), np.int64(1)}
Testing classes: {np.int64(2)}


# Shuffle obrigatório nesse caso

In [15]:
kf = KFold(n_splits=3, shuffle=True)

scores = cross_val_score(clf, X, y, cv=kf)
print(scores)

[0.96 0.98 0.98]


In [16]:
import numpy as np

for i, (tr_idxs, te_idxs) in enumerate(kf.split(X)):
    y_train = y[tr_idxs]
    y_test = y[te_idxs]

    train_class_counts = np.bincount(y_train)
    test_class_counts = np.bincount(y_test)

    print(f"Fold {i+1}:")
    print(f"  Training class counts: {train_class_counts}")
    print(f"  Testing class counts: {test_class_counts}")



Fold 1:
  Training class counts: [35 37 28]
  Testing class counts: [15 13 22]
Fold 2:
  Training class counts: [33 34 33]
  Testing class counts: [17 16 17]
Fold 3:
  Training class counts: [32 29 39]
  Testing class counts: [18 21 11]


# ...Ou usar o KFold estratificado.

In [22]:
from sklearn.model_selection import StratifiedKFold

kf = StratifiedKFold(n_splits=3, shuffle=False)

scores = cross_val_score(clf, X, y, cv=kf)
print(scores)

for i, (tr_idxs, te_idxs) in enumerate(kf.split(X, y)):
    y_train = y[tr_idxs]
    y_test = y[te_idxs]

    train_class_counts = np.bincount(y_train)
    test_class_counts = np.bincount(y_test)

    print(f"Fold {i+1}:")
    print(f"  Training class counts: {train_class_counts}")
    print(f"  Testing class counts: {test_class_counts}")

[0.98 0.98 0.98]
Fold 1:
  Training class counts: [33 33 34]
  Testing class counts: [17 17 16]
Fold 2:
  Training class counts: [33 34 33]
  Testing class counts: [17 16 17]
Fold 3:
  Training class counts: [34 33 33]
  Testing class counts: [16 17 17]


In [46]:
from sklearn.model_selection import StratifiedKFold

kf = StratifiedKFold(n_splits=3, shuffle=True)

scores = cross_val_score(clf, X, y, cv=kf)
print(scores)

for i, (tr_idxs, te_idxs) in enumerate(kf.split(X, y)):
    y_train = y[tr_idxs]
    y_test = y[te_idxs]

    train_class_counts = np.bincount(y_train)
    test_class_counts = np.bincount(y_test)

    print(f"Fold {i+1}:")
    print(f"  Training class counts: {train_class_counts}")
    print(f"  Testing class counts: {test_class_counts}")

[0.98 0.94 0.94]
Fold 1:
  Training class counts: [33 33 34]
  Testing class counts: [17 17 16]
Fold 2:
  Training class counts: [33 34 33]
  Testing class counts: [17 16 17]
Fold 3:
  Training class counts: [34 33 33]
  Testing class counts: [16 17 17]
