<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula06a_valida%C3%A7%C3%A3o_cruzada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

dataset = load_breast_cancer()
X, y = dataset.data, dataset.target
# inverte classes
target_names = dataset['target_names']
target_names[0], target_names[1] = target_names[1], target_names[0]
y = y*(-1)+1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(sum(y)/len(y))
print(sum(y_train)/len(y_train))
print(sum(y_test)/len(y_test))

0.37258347978910367
0.37142857142857144
0.37719298245614036


In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_train)
acc = accuracy_score(y_train, y_pred)
print(acc)

1.0


In [3]:
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(acc)

0.9298245614035088


In [4]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_train)
acc = accuracy_score(y_train, y_pred)
print(acc)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(acc)

0.9406593406593406
0.956140350877193


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None)
models = [KNeighborsClassifier(n_neighbors=1), KNeighborsClassifier(n_neighbors=5)]
for model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(acc)

0.9210526315789473
0.9035087719298246


# adendo numpy

In [19]:
type(X)

numpy.ndarray

In [20]:
type(X.shape)

tuple

In [21]:
X.shape

(569, 30)

In [24]:
import numpy as np
vetor = np.array([1,2,3])
vetor.shape

(3,)

In [25]:
matriz3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
matriz3d.shape

(3, 3, 3)

In [27]:
matriz4d = np.array([[[[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]],[[7,7,7],[8,8,8],[9,9,9]]],
                     [[[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]],[[7,7,7],[8,8,8],[9,9,9]]]])
matriz4d.shape

(2, 3, 3, 3)

# validação cruzada

In [47]:
idxs = range(X.shape[0])
for i in range(5):
  idx_b = i*X.shape[0]//5
  idx_e = (i+1)*X.shape[0]//5
  print(idxs[idx_b:idx_e], list(idxs[idx_b:idx_e]))

range(0, 113) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]
range(113, 227) [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215

In [63]:
model = KNeighborsClassifier()

idxs = range(X.shape[0])
acc_total = 0
for i in range(5):
  idx_b = i*X.shape[0]//5
  idx_e = (i+1)*X.shape[0]//5

  X_train_fold = np.delete(X, idxs[idx_b:idx_e], axis=0)
  y_train_fold = np.delete(y, idxs[idx_b:idx_e], axis=0)
  model.fit(X_train_fold, y_train_fold)

  X_test_fold = X[idxs[idx_b:idx_e]]
  y_test_fold = y[idxs[idx_b:idx_e]]
  y_pred = model.predict(X_test_fold)
  acc = accuracy_score(y_test_fold, y_pred)
  print(acc)
  acc_total += acc

print(f"\n{acc_total/5}")

0.8584070796460177
0.9210526315789473
0.9649122807017544
0.9473684210526315
0.9385964912280702

0.9260673808414843


# shuffle

In [75]:
model = KNeighborsClassifier()

idxs = list(range(X.shape[0]))
np.random.shuffle(idxs)
acc_total = 0
for i in range(5):
  idx_b = i*X.shape[0]//5
  idx_e = (i+1)*X.shape[0]//5

  X_train_fold = np.delete(X, idxs[idx_b:idx_e], axis=0)
  y_train_fold = np.delete(y, idxs[idx_b:idx_e], axis=0)
  model.fit(X_train_fold, y_train_fold)

  X_test_fold = X[idxs[idx_b:idx_e]]
  y_test_fold = y[idxs[idx_b:idx_e]]
  y_pred = model.predict(X_test_fold)
  acc = accuracy_score(y_test_fold, y_pred)
  print(acc)
  acc_total += acc

print(f"\n{acc_total/5}")

0.9380530973451328
0.9122807017543859
0.956140350877193
0.9122807017543859
0.9298245614035088

0.9297158826269213


In [85]:
from sklearn.model_selection import KFold

splitter = KFold(n_splits=5, shuffle=False)
acc_total = 0
for train_idx, test_idx in splitter.split(X):
  model = KNeighborsClassifier()
  model.fit(X[train_idx], y[train_idx])
  y_pred = model.predict(X[test_idx])
  acc = accuracy_score(y[test_idx], y_pred)
  print(acc)
  acc_total += acc

print(f"\n{acc_total/5}")

0.8596491228070176
0.9210526315789473
0.9649122807017544
0.9473684210526315
0.9380530973451328

0.9262071106970966


In [91]:
from sklearn.model_selection import cross_validate

model = KNeighborsClassifier()
results = cross_validate(model, X, y, cv=5)
print(results['test_score'])
print(np.mean(results['test_score']))

[0.88596491 0.93859649 0.93859649 0.94736842 0.92920354]
0.9279459711224964


In [92]:
from sklearn.model_selection import KFold

splitter = KFold(n_splits=5)
results = cross_validate(model, X, y, cv=splitter)
print(results['test_score'])
print(np.mean(results['test_score']))

[0.85964912 0.92105263 0.96491228 0.94736842 0.9380531 ]
0.9262071106970966


In [105]:
splitter = KFold(n_splits=5, shuffle=True)
results = cross_validate(model, X, y, cv=splitter)
print(results['test_score'])
print(np.mean(results['test_score']))

[0.93859649 0.93859649 0.9122807  0.94736842 0.91150442]
0.9296693060083838


# extratificação

In [115]:
from sklearn.model_selection import StratifiedKFold

splitter = StratifiedKFold(n_splits=5, shuffle=True)
results = cross_validate(model, X, y, cv=splitter)
print(results['test_score'])
print(np.mean(results['test_score']))

[0.9122807  0.95614035 0.94736842 0.92105263 0.92920354]
0.9332091290172333


# repeated cross-validation

In [121]:
from sklearn.model_selection import RepeatedStratifiedKFold

splitter = RepeatedStratifiedKFold(n_splits=5, n_repeats=10)
results = cross_validate(model, X, y, cv=splitter)
print(results['test_score'])
print(np.mean(results['test_score']))

[0.92982456 0.89473684 0.92982456 0.93859649 0.96460177 0.93859649
 0.92105263 0.92982456 0.93859649 0.96460177 0.92982456 0.93859649
 0.89473684 0.93859649 0.96460177 0.92982456 0.9122807  0.94736842
 0.94736842 0.92035398 0.94736842 0.92105263 0.89473684 0.92982456
 0.92035398 0.93859649 0.88596491 0.9122807  0.94736842 0.97345133
 0.90350877 0.94736842 0.92105263 0.92982456 0.96460177 0.88596491
 0.96491228 0.96491228 0.92982456 0.90265487 0.97368421 0.92105263
 0.90350877 0.94736842 0.92920354 0.92105263 0.96491228 0.93859649
 0.88596491 0.92920354]
0.9314795839155409


In [127]:
model1 = KNeighborsClassifier(n_neighbors=1)
model2 = KNeighborsClassifier(n_neighbors=5)

results1 = cross_validate(model1, X, y, cv=splitter)
results2 = cross_validate(model2, X, y, cv=splitter)

print(np.mean(results1['test_score']))
print(np.mean(results2['test_score']))


0.9166852973140815
0.931454743052321


# teste de significância estatística

In [130]:
from scipy.stats import ttest_ind

t_statistic, p_value = ttest_ind(results1['test_score'], results2['test_score'])
print("t_statistic", t_statistic)
print("p_value", p_value)

print()
alpha = 0.05
if p_value < alpha:
  print("Hipótese nula rejeitada")
else:
  print("Hipótese nula não rejeitada")

t_statistic -3.88007672208536
p_value 0.00018929633486295262

Hipótese nula rejeitada
