<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula16a_ensembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import fetch_olivetti_faces
from sklearn.model_selection import train_test_split
X, y = fetch_olivetti_faces(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data


In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [4]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_hits = knn_pred == y_test
print(knn_hits)
print(f"Accuracy: {knn_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.8625


In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)
gnb_hits = gnb_pred == y_test
print(gnb_hits)
print(f"Accuracy: {gnb_hits.mean()}")

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True False  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True False  True  True  True  True  True
  True False  True  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True False  True False  True  True
  True  True  True  True  True  True False  True]
Accuracy: 0.8375


In [7]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(eta0=0.1, random_state=42)
ppn.fit(X_train, y_train)
ppn_pred = ppn.predict(X_test)
ppn_hits = ppn_pred == y_test
print(ppn_hits)
print(f"Accuracy: {ppn_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True False  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
 False  True  True  True  True  True  True  True]
Accuracy: 0.875


In [8]:
import numpy as np
hits = np.stack((knn_hits, gnb_hits, ppn_hits))
print(hits.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False  True  True]
 [ True  True False]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [9]:
y_pred = np.array([knn_pred, gnb_pred, ppn_pred])
print(y_pred.T)

[[20 20 20]
 [28 28 28]
 [ 3  3  3]
 [21 21 21]
 [ 9  9  9]
 [ 8  8  8]
 [32 32 32]
 [ 9  9  9]
 [26 26 26]
 [12 16 12]
 [ 0  0 36]
 [36 36 36]
 [ 5  5  5]
 [ 7 15  7]
 [13 13 13]
 [ 4 34  4]
 [27 27 27]
 [37 37 37]
 [23 23 23]
 [38 38 38]
 [ 7  9  7]
 [ 1  1  1]
 [ 4 39 39]
 [25 27 27]
 [ 0  0  0]
 [ 3 39 39]
 [ 8 11 11]
 [22 22 22]
 [26 26 26]
 [10 15 10]
 [39 39 39]
 [14 19 19]
 [26 26 26]
 [ 5  5  5]
 [23 23 23]
 [11 11 11]
 [12 25 13]
 [20 34 34]
 [15 15 34]
 [14 14 14]
 [38 38 18]
 [ 5  5  5]
 [ 7  9  7]
 [ 2  2  9]
 [ 8  8  8]
 [38 38 38]
 [14 14 14]
 [18 18 18]
 [ 2  2  2]
 [17 39 17]
 [ 4  4 33]
 [32 32 32]
 [33 33 33]
 [ 7  9  7]
 [37 37 37]
 [ 3  3 24]
 [22 22 22]
 [17 17 17]
 [ 3  3  3]
 [ 0 15 15]
 [12 12 12]
 [29 29 29]
 [25 25 32]
 [17  0  7]
 [10 10 10]
 [14  3  3]
 [35 35 35]
 [26 12 27]
 [37 39 39]
 [ 7  9  7]
 [32 32 32]
 [14 14 14]
 [ 0  0 34]
 [ 4  4  4]
 [38 38 38]
 [24 24 24]
 [22 22 22]
 [36 36 36]
 [17  9 17]
 [28 28 28]]


In [10]:
from scipy.stats import mode
y_pred_mode, _ = mode(y_pred, axis=0)
vote_hits = y_pred_mode == y_test
print(vote_hits)
print(f"Accuracy: {vote_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9625


In [11]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers):
        self.classifiers = classifiers

    def fit(self, X, y):
        for _, clf in self.classifiers:
            clf.fit(X, y)
        return self

    def predict(self, X):
        y_preds = np.array([clf.predict(X) for _, clf in self.classifiers])
        y_pred_mode, _ = mode(y_preds, axis=0)
        return y_pred_mode

weak_classifiers = [
    ("knn", KNeighborsClassifier(n_neighbors=5)),
    ("gnb", GaussianNB()),
    ("ppn", Perceptron(eta0=0.1, random_state=42))
]
mv_clf = MajorityVoteClassifier(weak_classifiers)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = mv_clf_pred == y_test
print(mv_clf_hits)
print(f"Accuracy: {mv_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9625


In [13]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(weak_classifiers)
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(f"Accuracy: {voting_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9625


In [14]:
ks = [1, 5, 9]
weak_classifiers = [(f"KNN({k})", KNeighborsClassifier(k)) for k in ks]
mv_clf = MajorityVoteClassifier(weak_classifiers)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = mv_clf_pred == y_test
print(mv_clf_hits)
print(f"Accuracy: {mv_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.875


In [18]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
dt_clf_pred = dt_clf.predict(X_test)
dt_clf_hits = dt_clf_pred == y_test
print(dt_clf_hits)
print(f"Accuracy: {dt_clf_hits.mean()}")

[ True False  True  True  True False  True  True False False False  True
  True False False False False  True False  True  True  True False False
  True  True False False False False False  True False False  True False
 False False False  True False  True False False  True False  True  True
  True False False  True  True False  True False False False False  True
 False  True False False False  True  True False False False  True False
 False  True  True  True  True False  True False]
Accuracy: 0.4375


In [20]:
weak_classifiers = [(f"DT({i+1})", DecisionTreeClassifier()) for i in range(10)]
mv_clf = MajorityVoteClassifier(weak_classifiers)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = mv_clf_pred == y_test
print(mv_clf_hits)
print(f"Accuracy: {mv_clf_hits.mean()}")

[ True  True  True  True  True False  True  True False False False  True
  True False False False False  True  True  True  True  True False  True
  True  True False False False  True False  True False False False False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False  True  True  True  True False False  True  True
 False  True  True  True  True False  True  True]
Accuracy: 0.5375


In [30]:
dt_clf = DecisionTreeClassifier(splitter="random")
dt_clf.fit(X_train, y_train)
dt_clf_pred = dt_clf.predict(X_test)
dt_clf_hits = dt_clf_pred == y_test
print(dt_clf_hits)
print(f"Accuracy: {dt_clf_hits.mean()}")

[ True  True  True  True  True False  True False  True False False  True
  True  True  True False False False  True  True False  True False False
 False  True False False  True  True  True  True  True False  True  True
 False False  True  True False False  True False False  True  True False
  True  True False  True  True  True  True False False  True False  True
 False False False False  True False  True  True  True  True  True False
 False False  True  True False False  True  True]
Accuracy: 0.5625


In [34]:
weak_classifiers = [(f"DT({i+1})", DecisionTreeClassifier(splitter="random")) for i in range(10)]
mv_clf = MajorityVoteClassifier(weak_classifiers)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = mv_clf_pred == y_test
print(mv_clf_hits)
print(f"Accuracy: {mv_clf_hits.mean()}")

[ True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False False  True  True False  True  True  True  True False  True  True
  True  True False  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True  True False False  True  True
  True  True  True  True  True False  True  True]
Accuracy: 0.8375


In [42]:
from sklearn.ensemble import BaggingClassifier
base_classifier = DecisionTreeClassifier()
bag_clf = BaggingClassifier(base_classifier, n_estimators=10)
bag_clf.fit(X_train, y_train)
bag_clf_pred = bag_clf.predict(X_test)
bag_clf_hits = bag_clf_pred == y_test
print(bag_clf_hits)
print(f"Accuracy: {bag_clf_hits.mean()}")

[ True  True  True  True  True False  True  True  True False False  True
  True  True  True  True False  True  True  True  True  True  True False
  True  True  True  True  True False  True  True False  True False False
 False  True  True  True False  True  True  True False False  True  True
  True  True False  True  True False  True  True False  True  True  True
  True  True False False  True False  True  True False  True False  True
  True  True  True  True  True False  True  True]
Accuracy: 0.725


In [46]:
base_classifier = DecisionTreeClassifier(splitter="random")
bag_clf = BaggingClassifier(base_classifier, n_estimators=100)
bag_clf.fit(X_train, y_train)
bag_clf_pred = bag_clf.predict(X_test)
bag_clf_hits = bag_clf_pred == y_test
print(bag_clf_hits)
print(f"Accuracy: {bag_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True False False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9125


In [47]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train, y_train)
rf_clf_pred = rf_clf.predict(X_test)
rf_clf_hits = rf_clf_pred == y_test
print(rf_clf_hits)
print(f"Accuracy: {rf_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9375


In [48]:
from sklearn.ensemble import ExtraTreesClassifier
et_clf = ExtraTreesClassifier(n_estimators=100)
et_clf.fit(X_train, y_train)
et_clf_pred = et_clf.predict(X_test)
et_clf_hits = et_clf_pred == y_test
print(et_clf_hits)
print(f"Accuracy: {et_clf_hits.mean()}")

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.9875


In [60]:
from sklearn.ensemble import AdaBoostClassifier
base_classifier = DecisionTreeClassifier(splitter="random", max_depth=20)
ada_clf = AdaBoostClassifier(base_classifier)
ada_clf.fit(X_train, y_train)
ada_clf_pred = ada_clf.predict(X_test)
ada_clf_hits = ada_clf_pred == y_test
print(ada_clf_hits)
print(f"Accuracy: {ada_clf_hits.mean()}")
hits_train = ada_clf.predict(X_train) == y_train
# print(hits_train)
print(f"Train Accuracy: {hits_train.mean()}")


[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False  True  True False  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
Accuracy: 0.925
Train Accuracy: 1.0


In [65]:
from sklearn.ensemble import StackingClassifier
estimators = [
    ("ada", ada_clf),
    ("rf", rf_clf),
    ("et", et_clf)
]
stk_clf = StackingClassifier(
    estimators=estimators,
    cv=5
)
stk_clf.fit(X_train, y_train)
stk_pred = stk_clf.predict(X_test) == y_test
stk_hits = stk_pred == y_test
print(stk_hits)
print(f"Accuracy: {stk_hits.mean()}")
print(f"Train Accuracy: {(stk_clf.predict(X_train) == y_train).mean()}")

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


[False False False False False False False False False False  True False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
Accuracy: 0.025
Train Accuracy: 1.0


In [67]:
from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(shuffle=True, n_splits=5)
clf = ExtraTreesClassifier(n_estimators=100)
scores = cross_val_score(clf, X, y, cv=cv)
print(scores)
print(f"Accuracy: {scores.mean()}")

[0.9625 0.9875 0.9875 0.95   0.9625]
Accuracy: 0.9700000000000001


In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
clf = Pipeline(
    [
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression())
    ]
)
scores = cross_val_score(clf, X, y, cv=cv)
print(scores)
print(f"Accuracy: {scores.mean()}")

[1.     0.9625 0.9875 1.     0.9625]
Accuracy: 0.9825000000000002
