<a href="https://colab.research.google.com/github/fboldt/aulas-am-bsi/blob/main/aula11a_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_olivetti_faces

X, y = fetch_olivetti_faces(return_X_y=True)
print(X.shape)
print(y.shape)

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data
(400, 4096)
(400,)


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_hits = knn_pred == y_test
print(knn_hits)
print(knn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.8625


In [9]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)
gnb_hits = gnb_pred == y_test
print(gnb_hits)
print(gnb_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True False  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True False  True  True  True  True  True
  True False  True  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True False  True False  True  True
  True  True  True  True  True  True False  True]
0.8375


In [10]:
from sklearn.linear_model import Perceptron

ppn = Perceptron(eta0=0.1, random_state=42)
ppn.fit(X_train, y_train)
ppn_pred = ppn.predict(X_test)
ppn_hits = ppn_pred == y_test
print(ppn_hits)
print(ppn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True False  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
 False  True  True  True  True  True  True  True]
0.875


In [11]:
import numpy as np

hits = np.stack((knn_hits, gnb_hits, ppn_hits))
print(hits.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False  True  True]
 [ True  True False]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [12]:
y_pred = np.stack((knn_pred, gnb_pred, ppn_pred))
print(y_pred.T)

[[20 20 20]
 [28 28 28]
 [ 3  3  3]
 [21 21 21]
 [ 9  9  9]
 [ 8  8  8]
 [32 32 32]
 [ 9  9  9]
 [26 26 26]
 [12 16 12]
 [ 0  0 36]
 [36 36 36]
 [ 5  5  5]
 [ 7 15  7]
 [13 13 13]
 [ 4 34  4]
 [27 27 27]
 [37 37 37]
 [23 23 23]
 [38 38 38]
 [ 7  9  7]
 [ 1  1  1]
 [ 4 39 39]
 [25 27 27]
 [ 0  0  0]
 [ 3 39 39]
 [ 8 11 11]
 [22 22 22]
 [26 26 26]
 [10 15 10]
 [39 39 39]
 [14 19 19]
 [26 26 26]
 [ 5  5  5]
 [23 23 23]
 [11 11 11]
 [12 25 13]
 [20 34 34]
 [15 15 34]
 [14 14 14]
 [38 38 18]
 [ 5  5  5]
 [ 7  9  7]
 [ 2  2  9]
 [ 8  8  8]
 [38 38 38]
 [14 14 14]
 [18 18 18]
 [ 2  2  2]
 [17 39 17]
 [ 4  4 33]
 [32 32 32]
 [33 33 33]
 [ 7  9  7]
 [37 37 37]
 [ 3  3 24]
 [22 22 22]
 [17 17 17]
 [ 3  3  3]
 [ 0 15 15]
 [12 12 12]
 [29 29 29]
 [25 25 32]
 [17  0  7]
 [10 10 10]
 [14  3  3]
 [35 35 35]
 [26 12 27]
 [37 39 39]
 [ 7  9  7]
 [32 32 32]
 [14 14 14]
 [ 0  0 34]
 [ 4  4  4]
 [38 38 38]
 [24 24 24]
 [22 22 22]
 [36 36 36]
 [17  9 17]
 [28 28 28]]


In [13]:
from scipy.stats import mode

y_pred_mode, _ = mode(y_pred, axis=0)
vote_hits = y_pred_mode == y_test
print(vote_hits)
print(vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [14]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers):
        self.classifiers = classifiers

    def fit(self, X, y):
        for classifier in self.classifiers:
            classifier.fit(X, y)
        return self

    def predict(self, X):
        y_preds = []
        for classifier in self.classifiers:
            y_preds.append(classifier.predict(X))
        y_pred = np.stack(y_preds)
        y_pred_mode, _ = mode(y_pred, axis=0)
        return y_pred_mode

base_estimators = [knn, gnb, ppn]
majority_vote = MajorityVoteClassifier(base_estimators)
majority_vote.fit(X_train, y_train)
majority_vote_pred = majority_vote.predict(X_test)
majority_vote_hits = majority_vote_pred == y_test
print(majority_vote_hits)
print(majority_vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [15]:
from sklearn.ensemble import VotingClassifier

base_estimators = [
    ('knn', knn),
    ('gnb', gnb),
    ('ppn', ppn)
]
voting_classifier = VotingClassifier(base_estimators, voting='hard')
voting_classifier.fit(X_train, y_train)
voting_classifier_pred = voting_classifier.predict(X_test)
voting_classifier_hits = voting_classifier_pred == y_test
print(voting_classifier_hits)
print(voting_classifier_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [21]:
from pprint import pprint
base_estimators = [(f"kNN({i})", KNeighborsClassifier(i)) for i in range(1, 6, 2)]
pprint(base_estimators)
voting_classifier = VotingClassifier(base_estimators)
voting_classifier.fit(X_train, y_train)
voting_classifier_pred = voting_classifier.predict(X_test)
voting_classifier_hits = voting_classifier_pred == y_test
print(voting_classifier_hits)
print(voting_classifier_hits.mean())

[('kNN(1)', KNeighborsClassifier(n_neighbors=1)),
 ('kNN(3)', KNeighborsClassifier(n_neighbors=3)),
 ('kNN(5)', KNeighborsClassifier())]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True False  True  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.9


In [29]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)
dtc_hits = dtc_pred == y_test
print(dtc_hits)
print(dtc_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False  True  True False  True  True  True False False
  True  True False False False False False  True False False  True False
 False False False  True False False False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False  True  True  True  True False False False False
 False False  True  True  True False  True  True]
0.475


In [35]:
base_estimators = [
    ('knn', knn),
    #('gnb', gnb),
    ('ppn', ppn),
    ('dtc', dtc)
]
voting_classifier = VotingClassifier(base_estimators, voting='hard')
voting_classifier.fit(X_train, y_train)
voting_classifier_pred = voting_classifier.predict(X_test)
voting_classifier_hits = voting_classifier_pred == y_test
print(voting_classifier_hits)
print(voting_classifier_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True False  True  True  True  True  True  True  True  True  True
 False False  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.925


In [71]:
base_estimators = [(f"dtd({i})", DecisionTreeClassifier()) for i in range(10)]
voting_classifier = VotingClassifier(base_estimators)
voting_classifier.fit(X_train, y_train)
voting_classifier_pred = voting_classifier.predict(X_test)
voting_classifier_hits = voting_classifier_pred == y_test
print(voting_classifier_hits)
print(voting_classifier_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False  True  True False  True  True  True False  True
  True  True False False False False False  True  True False  True False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False False  True  True  True False False  True  True
 False  True  True  True  True False  True  True]
0.5375


In [72]:
dtc = DecisionTreeClassifier(splitter="random")
dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)
dtc_hits = dtc_pred == y_test
print(dtc_hits)
print(dtc_hits.mean())

[ True  True  True  True False  True False False  True False False  True
  True False  True  True False  True  True  True False  True False False
  True  True False False  True False False  True  True False  True False
 False  True  True  True False False  True  True  True  True  True  True
 False False  True False  True  True  True False  True  True  True False
  True  True False False  True False  True  True False False  True False
 False  True  True  True  True False  True  True]
0.6


In [73]:
base_estimators = [(f"dtd({i})", DecisionTreeClassifier(splitter="random")) for i in range(100)]
voting_classifier = VotingClassifier(base_estimators)
voting_classifier.fit(X_train, y_train)
voting_classifier_pred = voting_classifier.predict(X_test)
voting_classifier_hits = voting_classifier_pred == y_test
print(voting_classifier_hits)
print(voting_classifier_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False False  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True  True  True  True  True False  True  True
  True  True  True  True  True False  True  True]
0.875


In [74]:
from sklearn.ensemble import BaggingClassifier

base_estimator = KNeighborsClassifier(n_neighbors=1)
bagging_classifier = BaggingClassifier(base_estimator,
                                       n_estimators=100)
bagging_classifier.fit(X_train, y_train)
bagging_classifier_pred = bagging_classifier.predict(X_test)
bagging_classifier_hits = bagging_classifier_pred == y_test
print(bagging_classifier_hits)
print(bagging_classifier_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.925


In [75]:
base_estimator = DecisionTreeClassifier()
bagging_classifier = BaggingClassifier(base_estimator,
                                       n_estimators=10)
bagging_classifier.fit(X_train, y_train)
bagging_classifier_pred = bagging_classifier.predict(X_test)
bagging_classifier_hits = bagging_classifier_pred == y_test
print(bagging_classifier_hits)
print(bagging_classifier_hits.mean())

[ True  True  True  True  True False  True False  True False  True  True
  True  True  True  True False  True  True  True  True  True  True False
  True False  True  True  True False  True  True  True  True False  True
 False  True False  True False False  True  True  True False  True  True
  True False False  True  True False  True  True False False False  True
  True  True False False  True False  True  True False False  True False
  True False  True  True  True False  True  True]
0.6625


In [76]:
base_estimator = DecisionTreeClassifier(splitter="random")
bagging_classifier = BaggingClassifier(base_estimator,
                                       n_estimators=100)
bagging_classifier.fit(X_train, y_train)
bagging_classifier_pred = bagging_classifier.predict(X_test)
bagging_classifier_hits = bagging_classifier_pred == y_test
print(bagging_classifier_hits)
print(bagging_classifier_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True False  True False  True  True  True  True  True
  True  True False  True  True  True  True  True False  True  True  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.85


In [77]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_hits = rf_pred == y_test
print(rf_hits)
print(rf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False  True  True False  True False  True  True  True  True  True
  True  True  True  True  True False  True  True False  True  True  True
  True  True False False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.875


In [78]:
from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier(n_estimators=100)
etc.fit(X_train, y_train)
etc_pred = etc.predict(X_test)
etc_hits = etc_pred == y_test
print(etc_hits)
print(etc_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
0.975
